import pg from 'pg';

const { Client } = pg;

/**
 * Intelligent Auto-Mapping Script
 * Analyzes NAMASTE code descriptions to automatically suggest body region mappings
 */

const ANATOMICAL_PATTERNS = {
    head: [
        /head|shir[ao]|cranial|cerebr|brain|skull/i,
        /eye|netra|ophthalm|vision/i,
        /ear|karna|otic|hearing/i,
        /nose|nasik|nasal|sinus/i,
        /throat|kantha|pharyn|laryn/i,
        /neck|greeva|cervical/i,
        /migraine|headache/i
    ],
    chest: [
        /chest|uras|thorax|thoracic/i,
        /heart|hriday|cardiac|cardio/i,
        /lung|phupphus|pulmon|respirat/i,
        /breath|shwas|dyspnea/i,
        /cough|kas/i,
        /asthma/i
    ],
    abdomen: [
        /abdomen|udara|abdominal/i,
        /stomach|amashay|gastric|gastro/i,
        /liver|yakrit|hepat/i,
        /intestin|antra|bowel/i,
        /digest|pachan|agni/i,
        /kidney|vrikka|renal/i,
        /spleen|pliha/i,
        /pancreas/i
    ],
    pelvis: [
        /pelvi|kati|hip/i,
        /bladder|basti|urinary/i,
        /reproduct|garbh/i,
        /menstrual|artava/i,
        /uterus|garbhashay/i,
        /prostat/i
    ],
    arms: [
        /arm|bahu|upper.?limb/i,
        /shoulder|skandh/i,
        /elbow|karpara/i,
        /wrist|manibandh/i,
        /hand|hasta|palm/i,
        /finger|anguli/i
    ],
    legs: [
        /leg|pada|lower.?limb/i,
        /thigh|uru|femor/i,
        /knee|janu|patel/i,
        /ankle|gulpha/i,
        /foot|pada/i,
        /toe/i,
        /sciatica|gridhrasi/i
    ]
};

async function autoMapBodyRegions() {
    const client = new Client({
        host: 'localhost',
        port: 5432,
        database: 'ayush_fhir',
        user: 'postgres',
        password: 'hardik999'
    });

    try {
        console.log('🤖 Starting intelligent auto-mapping...\n');
        await client.connect();

        // Get all body regions
        const regionsResult = await client.query('SELECT id, code FROM body_regions');
        const regions = regionsResult.rows;

        // Get all NAMASTE codes
        const namasteResult = await client.query(`
            SELECT code, display, system_type 
            FROM namaste_codes 
            WHERE display IS NOT NULL
        `);

        let totalMappings = 0;
        let mappingsPerRegion = {};

        for (const region of regions) {
            const patterns = ANATOMICAL_PATTERNS[region.code] || [];
            let regionMappings = 0;

            for (const namasteCode of namasteResult.rows) {
                const text = `${namasteCode.display} ${namasteCode.code}`;

                // Check if any pattern matches
                let matchScore = 0;
                for (const pattern of patterns) {
                    if (pattern.test(text)) {
                        matchScore += 0.3; // Each match adds to confidence
                    }
                }

                if (matchScore > 0) {
                    // Calculate relevance score (cap at 1.0)
                    const relevanceScore = Math.min(matchScore, 1.0);

                    // Insert mapping
                    await client.query(`
                        INSERT INTO body_region_mappings 
                        (body_region_id, namaste_code, relevance_score, mapping_type, verified, notes)
                        VALUES ($1, $2, $3, $4, $5, $6)
                        ON CONFLICT DO NOTHING
                    `, [
                        region.id,
                        namasteCode.code,
                        relevanceScore.toFixed(2),
                        relevanceScore >= 0.7 ? 'primary' : 'secondary',
                        false,
                        'Auto-generated by NLP pattern matching'
                    ]);

                    regionMappings++;
                    totalMappings++;
                }
            }

            mappingsPerRegion[region.code] = regionMappings;
            console.log(`✓ ${region.code.padEnd(10)} → ${regionMappings} mappings created`);
        }

        console.log(`\n✅ Auto-mapping complete!`);
        console.log(`📊 Total mappings created: ${totalMappings}`);
        console.log(`\n💡 Next step: Restart backend server to load new routes`);
        console.log(`   Then visit the 3D Map to see the results!`);

        await client.end();
        process.exit(0);
    } catch (error) {
        console.error('❌ Auto-mapping failed:', error);
        await client.end();
        process.exit(1);
    }
}

autoMapBodyRegions();
